#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source $HOME/.asdf/asdf.sh

autoload -Uz bashcompinit

bashcompinit

source $HOME/.asdf/completions/asdf.bash
eval "$($HOME/Blake/bs/bin/bs init -)"
eval "$($HOME/Blake/bd/bin/bd init -)"
export PATH=$PATH:$HOME/Blake/bk8s/bin
source $HOME/Blake/bk8s/completions/bk.bash

export GOPATH=$HOME/go
PATH=$PATH:${GOPATH//://bin:}/bin

eval "$(mcfly init zsh)"
