#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
autoload -Uz compinit; compinit
autoload -Uz bashcompinit; bashcompinit

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -d "/opt/homebrew/bin" ]]; then
  export PATH="/opt/homebrew/bin:$PATH"
fi

if [[ -d "$HOME/.asdf/shims" ]]; then
  export PATH="$HOME/.asdf/shims:$PATH"
fi

if [[ -d "$HOME/Blake/bx/bin" ]]; then
  export PATH="$HOME/Blake/bx/bin:${PATH}"
fi

if [[ -d "$HOME/Blake/bk8s/bin" ]]; then
  export PATH="$HOME/Blake/bk8s/bin:${PATH}"
  source <(bk8s completion zsh)
fi

if [[ -d "$HOME/Blake/bp/bin" ]]; then
  export PATH="$HOME/Blake/bp/bin:${PATH}"
fi
